### ISSUE TITLE
Jumpers

### ISSUE THREAD

**Issue by pjbulls** [jakplugg/m-Brane#4]
Hiya,

how exactly do the jumpers work, particularly in v1.2? I can kind of guess that J13 and J14 support TRS MIDI A and B, but I have no idea what J11 and J12 are for...

**Comment by jakplugg** [comment]
J11 is in parallel with MIDI in and j12 is in parallel with MIDI out, in
case someone wanted to wire a 5 pin MIDI jack to the back of their case or
something like that.

**Comment by pjbulls** [comment]
Alright, thanks, that makes sense. I was trying to wrap my head around why you'd want to short those connections together, didn't think of just tapping them from these points.
